CREATE TABLE `USER` (
  `NAME` varchar(30) NOT NULL COMMENT '姓名',
  `AGE` int(11) NOT NULL COMMENT '年紀',
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`,`NAME`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
