version: '3'

services:

#  elasticsearch:
#    container_name: elasticsearch
#    image: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - ./es:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#
#  kibana:
#    container_name: kibana
#    image: kibana
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
