version: '3.1'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    ports:
       - 9200:9200
       - 9300:9300

  kibana:
    container_name: kibana
    image: kibana
    ports:
      - 5601:5601

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
