version: '3'

services:

  elk:
    container_name: elk
    image: sebp/elk:latest
    ports:
      - 9200:9200
      - 9300:9300
      - 5601:5601
      - 5044:5044
      - 4560:4560

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    restart: always
    ports:
      - 2181:2181