cluster.name: elasticsearch
node.name: node-master
node.master: true
node.data: true
http.port: 9200
network.host: 0.0.0.0
network.publish_host: 192.168.1.104
discovery.zen.ping.unicast.hosts: ["192.168.1.104"]